function T = metrics_to_table(restM, activeM)
%METRICS_TO_TABLE Convert metric structs to a simple table.

rows = { ...
    "Average HR (ECG)"; ...
    "Average HR (Video)"; ...
    "Relative error (avg)"; ...
    "MAE (aligned)"; ...
    "STD (ECG)"; ...
    "STD (Video)"; ...
    "Paired t-test p-value"; ...
    "Paired t-test h" ...
};

restVals = [ ...
    restM.mean_ecg; ...
    restM.mean_vid; ...
    restM.rel_err; ...
    restM.mae; ...
    restM.std_ecg; ...
    restM.std_vid; ...
    restM.ttest_p; ...
    restM.ttest_h ...
];

activeVals = [ ...
    activeM.mean_ecg; ...
    activeM.mean_vid; ...
    activeM.rel_err; ...
    activeM.mae; ...
    activeM.std_ecg; ...
    activeM.std_vid; ...
    activeM.ttest_p; ...
    activeM.ttest_h ...
];

T = table(rows, restVals, activeVals, 'VariableNames', {'Metric','Rest','Active'});
end
